title = "Simple Cipher"
blurb = "Implement the Vigenère cipher, a simple substitution cipher."
source = "Substitution Cipher at Wikipedia"
source_url = "https://en.wikipedia.org/wiki/Substitution_cipher"
